### ISSUE TITLE
provide binaries for UNIX and Windows

### ISSUE THREAD

**Issue by yeesian** [JuliaGeo/LibGEOS.jl#1]
@tkelman @staticfloat might you both be available during juliacon to help me out?

**Comment by staticfloat** [comment]
Unfortunately, I won't be at Juliacon.  :(

**Comment by tkelman** [comment]
Yeah I'll be there starting tomorrow morning. Gotta make sure I finish my slides first, which should be a good reference for this.

**Comment by yeesian** [comment]
:+1:  I'll be there

**Comment by yeesian** [comment]
closed by #7
