### ISSUE TITLE
Should this package be renamed to GEOS.jl?

### ISSUE THREAD

**Issue by yeesian** [JuliaGeo/LibGEOS.jl#10]
Following the [manual](http://julia.readthedocs.org/en/latest/manual/packages/) in

> Guidelines for naming a Package:
> [...]
> 6. Packages that wrap external libraries or programs should be named after those libraries or programs.
>    - CPLEX.jl wraps the CPLEX library, which can be identified easily in a web search.
>    - MATLAB.jl provides an interface to call the MATLAB engine from within Julia.

@garborg @c42f

**Comment by c42f** [comment]
Ah, the manual actually has a guideline?  In that case it certainly makes sense to do a rename.  I've found that the .jl package suffix convention makes it nice and easy to distinguish the julia wrapper from the underlying library on google.

**Comment by yeesian** [comment]
Okay, I'll be on board with the re-naming if @garborg is too

**Comment by garborg** [comment]
That sound fine to me... the other geo wrappers are getting non-'Lib' names these days, right @yeesian?

**Comment by yeesian** [comment]
> the other geo wrappers are getting non-'Lib' names these days, right @yeesian?

Yup, which is what made me change my mind about the 'Lib' stance. Let's do that with the `v0.1.0` minor release then?
