### ISSUE TITLE
bug in MultiPoint/MultiLineString

### ISSUE THREAD

**Issue by OmriRoames** [JuliaGeo/LibGEOS.jl#12]
The constructor of MultiPoint and MultiLineString using a Vector of points is broken. 
`LibGEOS.MultiPoint(Vector{Float64}[[0,0],[10,0],[10,10],[11,10]])`
results in the following error

> RROR: MethodError: `GEOSGeom_createCollection` has no method matching GEOSGeom_createCollection(::Int32, ::Ptr{Ptr{Ptr{Void}}}, ::Int64)
Closest candidates are:
  GEOSGeom_createCollection(::Int32, ::Ptr{Ptr{Ptr{Void}}}, ::UInt32)

It seems that the problem is that the function `createCollection(geomtype::Int, geoms::Vector{GEOSGeom})`  uses length(geoms) which returm an Int64 rather than UInt32

**Comment by yeesian** [comment]
closed by #13
