### ISSUE TITLE
Plotting through GeoInterface not working

### ISSUE THREAD

**Issue by skygering** [JuliaGeo/LibGEOS.jl#126]
When creating LibGEOS geometries, such as shapes and polygon, I am not able to plot using the standard Plots.jl commands, as is shown in [this example](https://discourse.julialang.org/t/compute-surfaces-of-intersection-between-circles-in-julia-with-libgeos/59811/3). When trying this I get the error: "Cannot convert LibGEOS.Polygon to series data for plotting". After posting this question on the Julia slack, I think it is due to the separation of plotting into the GeoInterfaceRecipes package, [like in this issue for GeoJSON](https://github.com/JuliaGeo/GeoJSON.jl/pull/46/files). Adding the GeoInterfaceRecipes package to my environment did not fix the problem.

**Comment by yeesian** [comment]
Thank you for filing the issue, yeah I can reproduce it too
