### ISSUE TITLE
STRtree memory management

### ISSUE THREAD

**Issue by jw3126** [JuliaGeo/LibGEOS.jl#140]
Looking at the code, it seems that unlike other objects STRtree does not have a finalizer for freeing memory. Is this by design or a bug? If by design, this should probably be documented?
https://github.com/JuliaGeo/LibGEOS.jl/blob/24724e0d590f31b4d1a3640e486f809ef6d84dd6/src/strtree.jl#L1-L5

**Comment by visr** [comment]
I think it was probably an oversight, we never discussed it in #115.

**Comment by jw3126** [comment]
fixed in https://github.com/JuliaGeo/LibGEOS.jl/pull/139
