### ISSUE TITLE
Is it expected that MultiPoint `within` a Polygon returns only a single true/false

### ISSUE THREAD

**Issue by alex-s-gardner** [JuliaGeo/LibGEOS.jl#188]
I would have expected LibGEOS.within(g1::MultiPoint, g2::POLYGON) to return a Bool of length(g1.geom), but this is not the case:

```julia
# specify 3 points
julia> g1 = GeoInterface.MultiPoint([(0.5, 0.5); (2., 2.); (0.25, 0.25)])
GeoInterface.Wrappers.MultiPoint{false, false, Vector{Tuple{Float64, Float64}}, Nothing, Nothing}([(0.5, 0.5), (2.0, 2.0), (0.25, 0.25)], nothing, nothing)

# create a Polygon
julia> g2 = readgeom("POLYGON((0 0,1 0,1 1,0 0))")
POLYGON ((0 0, 1 0, 1 1, 0 0))

# check if points are in polygon
julia> LibGEOS.within(g1, g2)
false
```

**Comment by evetion** [comment]
The above example does not work on my versions of the software. Nonetheless, this is expected, you ask whether a MultiPoint is within the Polygon (per docstring, whether a is in b -> bool), and it's not.

We could improve the documentation, predicates in Python have slightly better definitions, like 

> Returns True if geometry A is completely inside geometry B.

If you want to receive the individual results, split the multipoint into its individual points.
