### ISSUE TITLE
Base.normalize! on v0.4

### ISSUE THREAD

**Issue by visr** [JuliaGeo/LibGEOS.jl#19]
This function is new on v0.5, and not yet in Compat.jl.

We get this warning on julia v0.4
```
julia> using LibGEOS
WARNING: could not import Base.normalize! into LibGEOS
```

After JuliaLang/Compat.jl#253 is merged and tagged, we can take care of this, and bump our required Compat.jl version.

**Comment by yeesian** [comment]
thanks!
