### ISSUE TITLE
`parseWKT` gives Segmentation fault

### ISSUE THREAD

**Issue by OmriRoames** [JuliaGeo/LibGEOS.jl#20]
I'm trying to create a polygon from a WKT string which has additional content which makes julia crash.

``` julia
wkt = "SRID=32756; POLYGON ((481676.5592297933180816 7207446.6192339314147830, 481670.9812610360677354 7207436.6032548164948821, 481656.8734335989574902 7207443.3182328715920448, 481661.5463352609076537 7207453.9481827337294817, 481676.5592297933180816 7207446.6192339314147830))"

p=parseWKT(s)
```

gives:

 signal (11): Segmentation fault
unknown function (ip: (nil))
Segmentation fault

**Comment by yeesian** [comment]
I don't think LibGEOS supports the parsing of the Extended WKT format, but it will be nice for us to fail more gracefully. You might want to output standard WKT from PostGIS/databases for now. Seems related: https://trac.osgeo.org/gdal/ticket/1230

**Comment by OmriRoames** [comment]
Are you happy with some simple string validation in `geomFromWKT`?

**Comment by yeesian** [comment]
I'd rather we move towards the new reader and writer functions mentioned in #21.
