### ISSUE TITLE
segmentation fault in Point constructor

### ISSUE THREAD

**Issue by OmriRoames** [JuliaGeo/LibGEOS.jl#24]
I'm getting a seg fault when I'm creating a point with integers

```julia
Point(2, 3)
```

results in 

signal (11): Segmentation fault
while loading no file, in expression starting on line 0
unknown function (ip: 0xffffffffffffffff)
Type at /home/omri/.julia/v0.5/LibGEOS/src/geos_types.jl:10
unknown function (ip: 0x7fd1367347cc)
jl_call_method_internal at /build/julia-c0WfgE/julia-0.5.0/src/julia_internal.h:189 [inlined]
jl_apply_generic at /build/julia-c0WfgE/julia-0.5.0/src/gf.c:1942
do_call at /build/julia-c0WfgE/julia-0.5.0/src/interpreter.c:66
eval at /build/julia-c0WfgE/julia-0.5.0/src/interpreter.c:190
jl_toplevel_eval_flex at /build/julia-c0WfgE/julia-0.5.0/src/toplevel.c:558 [inlined]
jl_toplevel_eval at /build/julia-c0WfgE/julia-0.5.0/src/toplevel.c:580
jl_toplevel_eval_in_warn at /build/julia-c0WfgE/julia-0.5.0/src/builtins.c:590
eval at ./boot.jl:234
unknown function (ip: 0x7fd34530f67f)
jl_call_method_internal at /build/julia-c0WfgE/julia-0.5.0/src/julia_internal.h:189 [inlined]
jl_apply_generic at /build/julia-c0WfgE/julia-0.5.0/src/gf.c:1942
eval_user_input at ./REPL.jl:64
unknown function (ip: 0x7fd13672cdb6)
jl_call_method_internal at /build/julia-c0WfgE/julia-0.5.0/src/julia_internal.h:189 [inlined]
jl_apply_generic at /build/julia-c0WfgE/julia-0.5.0/src/gf.c:1942
macro expansion at ./REPL.jl:95 [inlined]
#3 at ./event.jl:68
unknown function (ip: 0x7fd136729f2f)
jl_call_method_internal at /build/julia-c0WfgE/julia-0.5.0/src/julia_internal.h:189 [inlined]
jl_apply_generic at /build/julia-c0WfgE/julia-0.5.0/src/gf.c:1942
jl_apply at /build/julia-c0WfgE/julia-0.5.0/src/julia.h:1392 [inlined]
start_task at /build/julia-c0WfgE/julia-0.5.0/src/task.c:253
unknown function (ip: 0xffffffffffffffff)
Allocations: 2023301 (Pool: 2022391; Big: 910); GC: 1
Segmentation fault

**Comment by OmriRoames** [comment]
We should either support it or have fail with a sensible error

**Comment by OmriRoames** [comment]
Also `Point(1,2)` doesn't segfault. Getting the coordinates `LibGEOS.coordinates(Point(1,2))`
results in 
2-element Array{Float64,1}:
 0.0
 0.0

I think that it all comes down to an ambiguity between `createCoordSeq(size::Integer, ndim::Integer)` and `createCoordSeq(x::Real, y::Real)`

**Comment by yeesian** [comment]
Thanks for the bug reports and PR!

Can you change the `ndim` argument in `createCoordSeq(size::Integer, ndim::Integer)` to a keyword argument (i.e. `createCoordSeq(size::Integer; ndim::Integer)`), and see if you can address this issue in #26 too?

**Comment by OmriRoames** [comment]
sure

**Comment by OmriRoames** [comment]
yeah, that works

**Comment by yeesian** [comment]
Okay let's go with it.
