### ISSUE TITLE
Ambiguity in createCoordSeq

### ISSUE THREAD

**Issue by OmriRoames** [JuliaGeo/LibGEOS.jl#27]
There are currently two methods `createCoordSeq` that accepts 2 integers (since Integer <: Real). This causes 
``` julia
LibGEOS.getCoordinates(LibGEOS.createCoordSeq(1,2))
```
to return 
1-element Array{Array{Float64,1},1}:
 [0.0,0.0]

and 
```julia
LibGEOS.getCoordinates(LibGEOS.createCoordSeq(1.0,2.0))
``` 
to return 
1-element Array{Array{Float64,1},1}:
 [1.0,2.0]

Which is very counter intuitive and also cases a segmentation fault when creating a Point with integers (see #24 )

There are a few ways to fix this. The one I think is most suitable is:
make  createCoordSeq(size::Integer, ndim::Integer) privet i.e. _createCoordSeq(size::Integer, ndim::Integer)

Any thought @yeesian ?

**Comment by yeesian** [comment]
https://github.com/JuliaGeo/LibGEOS.jl/issues/24#issuecomment-259336038
