### ISSUE TITLE
Point(2,3)  crashed

### ISSUE THREAD

**Issue by zhangliye** [JuliaGeo/LibGEOS.jl#28]
p1 = Point( 2, 3 )     

the Julia command console crashed.  

This may be caused by no existing matching function of Point( x::Int, y::Int ) in geos_types.jl.

# running on Win7, Julia 5.0, LibGEOS v0.1.0

**Comment by yeesian** [comment]
Might be a dup of https://github.com/JuliaGeo/LibGEOS.jl/issues/25. Can you checkout https://github.com/JuliaGeo/LibGEOS.jl/pull/26 and see if it works for you?
