### ISSUE TITLE
use later version of GEOS

### ISSUE THREAD

**Issue by evetion** [JuliaGeo/LibGEOS.jl#35]
The GEOS 3.4.2 was released in 2013. Please use 3.4.3 or newer versions such as 3.5 or 3.6.

See https://trac.osgeo.org/geos/ for versions and http://download.osgeo.org/geos/ for downloads.

**Comment by yeesian** [comment]
👍

Will you like to attempt a PR for this?

**Comment by visr** [comment]
@yeesian for the Windows side of this, which comes from https://build.opensuse.org/project/show/home:yeesian, is there any way we can help updating? I'd like to update GDAL to 2.2 as well.

**Comment by evetion** [comment]
I could attempt a PR to change 1 character. Should be able to figure it out.
However, the main problem is with the windows build, from your own repository.

**Comment by yeesian** [comment]
Might it be a good idea to move to a Conda-based setup for windows?

**Comment by yeesian** [comment]
> However, the main problem is with the windows build, from your own repository.

I'd like to try and increase the bus factor of this package, haha. If you don't mind, can you try mirroring the setup in https://build.opensuse.org/package/show/home:airbus-geo/geos and point [the URL](https://github.com/JuliaGeo/LibGEOS.jl/blob/master/deps/build.jl#L18) there?

**Comment by visr** [comment]
@yeesian the conda option seems tempting, but the risk is to run into issues like this
https://github.com/JuliaIO/HDF5.jl/issues/323#issuecomment-241208739

Since you already put the work into setting up an OBS let's stick with that for now?

**Comment by evetion** [comment]
My shortest PR yet (can it be smaller?) https://github.com/JuliaGeo/LibGEOS.jl/pull/36

**Comment by yeesian** [comment]
> for the Windows side of this, which comes from https://build.opensuse.org/project/show/home:yeesian, is there any way we can help updating? I'd like to update GDAL to 2.2 as well.

@visr can you set up an OBS account and try replicating the setup in https://build.opensuse.org/package/show/Application:Geo/gdal for GDAL as well?

I'll try updating the binaries for LibGEOS now.

**Comment by evetion** [comment]
Everything seems to build. Created second PR to use version 3.6.1. https://github.com/JuliaGeo/LibGEOS.jl/pull/37

**Comment by visr** [comment]
@yeesian I do have an account on OBS, also with id [visr](https://build.opensuse.org/user/show/visr).

Thanks for updating both GEOS and GDAL on OBS!

**Comment by yeesian** [comment]
closed by #37
