### ISSUE TITLE
Provide more informative error messages

### ISSUE THREAD

**Issue by yeesian** [JuliaGeo/LibGEOS.jl#41]
ref #40 #24 #20

**Comment by visr** [comment]
Would be a big help indeed. Shouldn't be too complicated.
See for instance GEOSContext_setErrorMessageHandler_r in https://geos.osgeo.org/doxygen/geos__c_8h_source.html

So we should be able to do something similar to https://github.com/visr/GDAL.jl/blob/54160bbd0f49f7f1f80c33947b0016d7d19c4314/src/GDAL.jl#L84-L85

**Comment by yeesian** [comment]
Thanks for the pointers Martijn
