### ISSUE TITLE
0.3.0 compilation failure on deps.jl

### ISSUE THREAD

**Issue by rickedanielson** [JuliaGeo/LibGEOS.jl#50]
`Pkg.add("LibGEOS")` on a 2017-12-13 (d386e40) install of Julia 0.6.2 on Linux Mint 17.3 yields the compilation error

```
LoadError: BinaryProvider.LibraryProduct("/home/x/.julia/v0.6/LibGEOS/deps/usr/lib", String["libgeos_c"], :libgeos, "Prefix(/home/x/.julia/v0.6/LibGEOS/deps/usr)") is not satisfied, cannot generate deps.jl!
while loading /home/x/.julia/v0.6/LibGEOS/deps/build.jl, in expression starting on line 38
```

The temporary solution seems to be
`Pkg.pin("LibGEOS", v"0.2.1")`
`Pkg.build("LibGEOS")`

but no error occurs on Mint 18.2, which points to libgeos-3.6.1.so and libgeos_c.so.1.10.1 (whereas Mint 17.3 points to libgeos-3.6.2.so and libgeos_c.so.1.10.2)

**Comment by yeesian** [comment]
Thanks! What if you ran `Pkg.checkout("LibGEOS"); Pkg.build("LibGEOS")`?

**Comment by rickedanielson** [comment]
On 0.3.0 master the same message (different line) is

LoadError: BinaryProvider.LibraryProduct("/home/x/.julia/v0.6/LibGEOS/deps/usr/lib", String["libgeos_c"], :libgeos, "Prefix(/home/x/.julia/v0.6/LibGEOS/deps/usr)") is not satisfied, cannot generate deps.jl!
while loading /home/x/.julia/v0.6/LibGEOS/deps/build.jl, in expression starting on line 42

**Comment by visr** [comment]
Hmm that is unfortunate, not sure why it worked on CI but not for you. Just restarted Travis CI as well on master. One more thing to check (on master), is to remove any possible old stuff (everything but build.jl) from the deps folder. Older versions did not keep track of what was installed, things might have gotten messy.

**Comment by rickedanielson** [comment]
Using the 0.3.0 package with the 0.2.1 `build.jl` file (i.e., using BinDeps rather than BinaryProvider) is perhaps a better temporary solution:

```
Pkg.pin("LibGEOS", v"0.2.1") ; Pkg.build("LibGEOS") ; cp ~/.julia/v0.6/LibGEOS/deps/build.jl ~
Pkg.rm("LibGEOS") ; Pkg.rm("LibGEOS") ; Pkg.add("LibGEOS")
cd ~/.julia/v0.6/LibGEOS/deps ; mv build.jl build.jl.ori ; mv ~/build.jl . ; touch -r build.jl.ori build.jl
Pkg.build("LibGEOS")
```

**Comment by rickedanielson** [comment]
I'll just link to [#105](https://github.com/JuliaOpt/Ipopt.jl/issues/105) as possibly related and close (since there's no apparent issue with CI).

**Comment by visr** [comment]
Hmm ok well if you think there is something we can do to fix this, do let us know!
