### ISSUE TITLE
How to write to WKB?

### ISSUE THREAD

**Issue by huaxk** [JuliaGeo/LibGEOS.jl#60]
```
p1 = readgeom("POLYGON((0 0,1 0,1 1,0 0))")
writegeom(p1)
```
got a WKT string: ` "POLYGON((0 0,1 0,1 1,0 0))"`
but how can i write to WKB, whatever bits string or hex string.

**Comment by visr** [comment]
Hmm yes we test mainly with WKT, the WKB experience could be improved.

I have an example below, but needed to remove the `::Ptr{Csize_t}` restriction after `size` here for it to enter that method:
https://github.com/JuliaGeo/LibGEOS.jl/blob/8a9b17b7e9a445ddcb1be5b8e617ce41089f39fd/src/geos_c.jl#L1305

Then it becomes:

```julia
using LibGEOS
wkbwriter = LibGEOS.WKBWriter(LibGEOS._context)
p1 = readgeom("POLYGON((0 0,1 0,1 1,0 0))")
writegeom(p1, wkbwriter)  # -> 77-element Array{UInt8,1}
```

We probably should both make a `WKBWriter` constructor with the default context such that we can just do `wkbwriter = LibGEOS.WKBWriter()`.
We can chop off the the single `::Ptr{Csize_t}` now, but there seem to be many more. A better option but some more work is to regenerate the bindings with Clang.jl, which has been much improved recently.

**Comment by huaxk** [comment]
```
using LibGEOS
wkbwriter = LibGEOS.WKBWriter(LibGEOS._context)
p1 = readgeom("POLYGON((0 0,1 0,1 1,0 0))")
writegeom(p1, wkbwriter)
```
geos_c.jl:1306:
`ccall((:GEOSWKBWriter_write_r,libgeos),Ptr{Cuchar},(GEOSContextHandle_t,Ptr{GEOSWKBWriter},Ptr{GEOSGeometry},Ptr{Csize_t}),handle,writer,g,size)`
thers is an error:
param size type is Ptr{Csize_t}, don't accept type Base.RefValue{Csize_t}

modify _writegeom at geos_functions.jl:27 to solve this problem:
```
function _writegeom(geom::GEOSGeom, wkbwriter::WKBWriter, context::GEOSContext = _context)
               wkbsize = Ptr{Csize_t}(pointer_from_objref(Ref{Csize_t}()))
               result = GEOSWKBWriter_write_r(context.ptr, wkbwriter.ptr, geom, psize)
               unsafe_wrap(Array, result, wkbsize[], own=true)
 end
```
Is that ok?

**Comment by visr** [comment]
I think the right solution is to remove `::Ptr{Csize_t}` from the function argument instead. You can try out the wrap branch, where this is already done: `pkg> add LibGEOS#wrap`.

> param size type is Ptr{Csize_t}, don't accept type Base.RefValue{Csize_t}

I can see why you'd think this, but that's not true. From the [Ref docs](https://docs.julialang.org/en/latest/base/c/#Core.Ref):
> When passed as a ccall argument (either as a Ptr or Ref type), a Ref object will be converted to a native pointer to the data it references.

Also have a look at https://docs.julialang.org/en/latest/manual/calling-c-and-fortran-code/#Garbage-Collection-Safety-1 to see why passing the `Ref` to `ccall` is a safer solution.

**Comment by huaxk** [comment]
That's ok, thank you for your work!
