### ISSUE TITLE
writegeom precision vs significant digits on geometries with setPrecision applied

### ISSUE THREAD

**Issue by jaakkor2** [JuliaGeo/LibGEOS.jl#86]
LibGEOS.jl v0.6.6 exposed the WKTWriter options https://github.com/JuliaGeo/LibGEOS.jl/pull/82, and set the default `roundingprecision::Int=-1`, i.e., disabled as per https://geos.osgeo.org/doxygen/classgeos_1_1io_1_1WKTWriter.html#a55b7fd9ffcec35f7a4f823a0c9464dce.

Now with LibGEOS.jl v.0.6.6 and GEOS_jll v3.9.0+0
```
using LibGEOS
p = readgeom("POINT (654321.12345 0.12345)")
p0 = setPrecision(p, 0); # floating precision
writegeom(p0)
```
gives
```
"POINT (654321.12345 0.12345)"
```
but setting the grid size to `0.02`
```
p2 = setPrecision(p, 0.02);
writegeom(p2)
```
gives
```
"POINT (6.5e+05 0.12)"
```
and
```
p4 = setPrecision(p, 0.0001);
writegeom(p4)
"POINT (6.543e+05 0.1235)"
```
I.e., huge loss of precision, looks like number of significant digits is coming from the grid size.

However,
```
writer = LibGEOS.WKTWriter(LibGEOS._context, trim=false, roundingprecision=-1);
writegeom(p2, writer)
"POINT (654321.12 0.12)"
```
seems to work as expected.  But this not
```
writer = LibGEOS.WKTWriter(LibGEOS._context, trim=true, roundingprecision=-1);
writegeom(p2, writer)
"POINT (6.5e+05 0.12)"
```

So, somehow it is related to trimming.

**Comment by visr** [comment]
Here I don't fully understand why it is only fixed format when trim is not true:
https://github.com/libgeos/geos/blob/5b722cfd7c0dc7f3a5e205928397f304c60daf10/src/io/WKTWriter.cpp#L358-L369
It seems to me that that the number of decimal places then becomes used as the number of significant digits, which for a large number such as `654321.12345` is very different.

In the GEOS docs it describes `trim` with: "Enables/disables trimming of unnecessary decimals". And that is not what it seems to be doing here. Perhaps best to raise an issue at GEOS itself?

**Comment by visr** [comment]
I'll close this, as this is now fixed in the GEOS master branch.
