### ISSUE TITLE
Remaining steps to v0.1.0

### ISSUE THREAD

**Issue by yeesian** [JuliaGeo/LibGEOS.jl#9]
- [x] [README] Installation instructions, after v0.0.3 is tagged in METADATA
- [x] [README] Travis/Coveralls/PkgEval badges
- [ ] [documentation] provide more examples, perhaps in a separate website
- [ ] [documentation] list exported/public functions and their signatures
- ~~[ ] change name from LibGEOS.jl to GEOS.jl (see #10)~~

**Comment by visr** [comment]
Shall I go ahead and tag v0.1.0? Would be nice to have a good version for julia v0.5, we can handle the other issues later.

**Comment by yeesian** [comment]
Sure, thanks!
