### ISSUE TITLE
Access to `GEOSGeom_getXMin`, `GEOSGeom_getXMax`, `GEOSGeom_getYMin` and `GEOSGeom_getYMax`

### ISSUE THREAD

**Issue by mathieu17g** [JuliaGeo/LibGEOS.jl#93]
@visr I have not found functions giving access to `GEOSGeom_getXMin`, `GEOSGeom_getXMax`, `GEOSGeom_getYMin` and `GEOSGeom_getYMax`, shall I make a PR with functions wrapping libgoes_api.jl functions like something as below: 

```julia 
function getXMin(ptr::GEOSGeom, context::GEOSContext = _context)
    result = GEOSGeom_getXMin_r(context.ptr, ptr)
    if result == C_NULL
        error("LibGEOS: Error in GEOSGeom_getXMin_r")
    end
    result
end

for geom in (:Point, :MultiPoint, :LineString, :MultiLineString, :LinearRing, :Polygon, :MultiPolygon, :GeometryCollection)
    @eval getXMin(obj::$geom) = getXMin(obj.ptr)
end
```

**Comment by visr** [comment]
Yeah, that looks consistent with the rest of the code, would be great if you could add it.

**Comment by mathieu17g** [comment]
@visr I would like to also add an access to `GEOSGeom_getExtent`. Unfortunately, it is not generated in libgeos_api.jl. Something looking like the function below is missing.

```julia
function GEOSGeom_getExtent_r(handle, g, xmin, ymin, xmax, ymax)
    ccall((:GEOSGeom_getExtent_r, libgeos), Cint, (GEOSContextHandle_t, Ptr{GEOSGeometry}, Ptr{Cdouble}, Ptr{Cdouble}, Ptr{Cdouble}, Ptr{Cdouble}), handle, g, xmin, ymin, xmax, ymax)
end
```

Could you tell me how to add `GEOSGeom_getExtent_r` to the API ?

**Comment by visr** [comment]
Ah I see. I'm not sure why it's not there, is this a function that was recently added? The `libgeos_api.jl` is generated by `gen/generate.jl`. If you activate the `gen` environment and run that script, does it get added? Right now the dependencies are pinned in the Manifest.toml, but it may also be good to try the latest Clang.jl release, e.g. do a `] up` of the `gen` environment.

**Comment by visr** [comment]
See #94, where I update the generator.

**Comment by mathieu17g** [comment]
Yes I have regenerated it locally also and the function does not appear in lingoes_api.jl, although it is present in geos_c.h.in

https://github.com/libgeos/geos/blob/1e60dbd83f7525e844e90b518ff1cc1f1f5bf695/capi/geos_c.h.in#L1521-L1528

**Comment by jaakkor2** [comment]
`GEOSGeom_getExtent_r` was added only three weeks ago https://github.com/libgeos/geos/pull/555 , and there
is no release since then.

**Comment by mathieu17g** [comment]
@jaakkor2 thanks I could not find any time of introduction in GitHub geos repository and I supposed it was an old function used by Shapely for its geometry `bounds` attribute
